os.loadAPI("CCKit/hires.lua")
hires.initGraphics()
local file = fs.open("CCKit/testimage.lon", "r")
local image = textutils.unserialize(file.readAll())
file.close()
hires.drawCapture(1, 1, image)
os.sleep(5)
hires.endGraphics()
os.unloadAPI("hires")